--------------------------------------------------------
--  DDL for Package PKG_UTIL
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PTOVENTA"."PKG_UTIL" IS

    NO_EXISTE_PADRE EXCEPTION;
    PRAGMA EXCEPTION_INIT(NO_EXISTE_PADRE, -2291);
    NO_EXISTE_PADRE_NUM NUMBER := -2291;
    NO_EXISTE_PADRE_MSG VARCHAR2(76) := 'No existe Tabla Padre';

    EXISTE_HIJO EXCEPTION;
    PRAGMA EXCEPTION_INIT(EXISTE_HIJO, -2292);
    EXISTE_HIJO_NUM NUMBER := -2291;
    EXISTE_HIJO_MSG VARCHAR2(76) := 'Existe(n) Tabla(s) Hija(a)';

    GRANDE_PARA_COLUMNA EXCEPTION;
    PRAGMA EXCEPTION_INIT(GRANDE_PARA_COLUMNA, -1401);
    GRANDE_PARA_COLUMNA_NUM NUMBER := -1401;
    GRANDE_PARA_COLUMNA_MSG VARCHAR2(76) := 'Dato ingresado excede el tama?o permitido';

    TYPE TIPO_ARREGLO IS TABLE OF VARCHAR2(1500) INDEX BY BINARY_INTEGER;
    TYPE TYP_MATRIZ IS TABLE OF TIPO_ARREGLO INDEX BY BINARY_INTEGER;
    TYPE CURSOR_TYPE IS REF CURSOR;

    PROCEDURE SP_ARREGLO
    (
        P_ARREGLO     VARCHAR2,
        P_SALIDA      OUT TIPO_ARREGLO,
        P_COMPONENTES OUT INT,
        P_SEPARADOR   CHAR DEFAULT '|'
    );

    FUNCTION FN_SEGMENTO
    (
        A_CADENA    VARCHAR2,
        A_ITEM      INT,
        A_SEPARADOR CHAR DEFAULT '|'
    ) RETURN VARCHAR2;

    
END PKG_UTIL;

/
