CREATE OR REPLACE TRIGGER PTOVENTA.TGR_VALIDA_IVTA_SAP
	BEFORE UPDATE
	OF NUM_COMP_PAGO
	ON VTA_COMP_PAGO
FOR EACH ROW


when ( new.NUM_COMP_PAGO<> old.NUM_COMP_PAGO AND NOT old.FEC_PROCESO_SAP IS NULL)
DECLARE
begin
  RAISE_APPLICATION_ERROR(-20000,'No se puede cambiar correlativos una vez procesados en SAP');
end;
/

