--------------------------------------------------------
--  DDL for Package PTOVTA_MATRIZ_CONV_BTLMF
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PTOVENTA"."PTOVTA_MATRIZ_CONV_BTLMF" AS

  PANTALLA_ABA_PIXEL_ALTO  VARCHAR2(30) := 'PANT_ABA_PIX_ALTO';
  PANTALLA_ABA_PIXEL_ANCHO VARCHAR2(30) := 'PANT_ABA_PIX_ANCHO';
  PANTALLA_DER_PIXEL_ALTO  VARCHAR2(30) := 'PANT_DER_PIX_ALTO';
  PANTALLA_DER_PIXEL_ANCHO VARCHAR2(30) := 'PANT_DER_PIX_ANCHO';
  PANTALLA_IZQ_PIXEL_ALTO  VARCHAR2(30) := 'PANT_IZQ_PIX_ALTO';
  PANTALLA_IZQ_PIXEL_ANCHO VARCHAR2(30) := 'PANT_IZQ_PIX_ANCHO';

  COD_DATO_CONV_REPARTIDOR  VARCHAR2(10) := 'D_001';
  COD_DATO_CONV_MEDICO      VARCHAR2(10) := 'D_005';
  COD_DATO_CONV_ORIG_RECETA VARCHAR2(10) := 'D_002';

  COD_DATO_CONV_DIAGNOSTICO_UIE VARCHAR2(10) := 'D_004';
  COD_DATO_CONV_BENIFICIARIO    VARCHAR2(10) := 'D_000';

  OBJ_IN_TEXTO       VARCHAR2(30) := 'INGRESO_TEXTO';
  OBJ_LISTA_PANTALLA VARCHAR2(30) := 'LISTA_PANTALLA';
  OBJ_LISTA_COMBO    VARCHAR2(30) := 'LISTA_COMBO';

  CONS_NRO_RESOLUCION VARCHAR2(20) := '800x600';

  FLG_RETENCION CHAR(1) := '0';

  ---VARIABLES JQUISPE 23.12.2011
  C_ESTADO_ACTIVO CHAR(1) := 'A';

  TYPE TYP_ARR_VARCHAR is table of VARCHAR2(100) index by PLS_INTEGER;

  FUNCTION CON_AGREGA_DATOS_TMP(cCodGrupoCia_in CHAR,
                              cCodLocal_in    CHAR,
                              cNumPedVta_in   CHAR) RETURN CHAR;

END;

/
