CREATE OR REPLACE FORCE VIEW PTOVENTA.V_CON_PREC_TOTAL AS
SELECT
/*+ RULE*/SUBSTR(MSG,1,10) COD_CONVENIO,
SUBSTR(MSG,11,6) COD_PROD_SAP,
TO_NUMBER(SUBSTR(MSG,17,10),'999999.999') PRECIO_CONV,
SUBSTR(MSG,27,1) FLG_FRACCIONAMIENTO,
SUBSTR(MSG,28,1) ESTADO,
SUBSTR(MSG,29,10) COD_PETITORIO
FROM ET_LISTADO4
union
select null,null,null,null,null,null
from   dual;

