create or replace force view ptoventa.v_pbl_usu_local as
select "COD_GRUPO_CIA","COD_LOCAL","SEC_USU_LOCAL","LOGIN_USU","COD_TRAB","COD_CIA","NOM_USU","APE_PAT","APE_MAT","CLAVE_USU","TELEF_USU","DIRECC_USU","FEC_NAC","EST_USU","FEC_CREA_USU_LOCAL","USU_CREA_USU_LOCAL","FEC_MOD_USU_LOCAL","USU_MOD_USU_LOCAL","IND_DISTR_GRATUITA","DNI_USU","COD_TRAB_RRHH","CARNE_SANIDAD","FEC_EXPEDICION","FEC_VENCIMIENTO","FEC_ULT_CAMB_CLAVE" from ptoventa.pbl_usu_local;

