create or replace force view ptoventa.v_vta_forma_pago_pedido as
select "COD_GRUPO_CIA","COD_LOCAL","COD_FORMA_PAGO","NUM_PED_VTA","IM_PAGO","TIP_MONEDA","VAL_TIP_CAMBIO","VAL_VUELTO","IM_TOTAL_PAGO","NUM_TARJ","FEC_VENC_TARJ","NOM_TARJ","FEC_CREA_FORMA_PAGO_PED","USU_CREA_FORMA_PAGO_PED","FEC_MOD_FORMA_PAGO_PED","USU_MOD_FORMA_PAGO_PED","CANT_CUPON","TIPO_AUTORIZACION","COD_LOTE","COD_AUTORIZACION","DNI_CLI_TARJ","COD_CIA","IND_ANUL_LOTE_CERRADO" from ptoventa.VTA_FORMA_PAGO_PEDIDO;

