CREATE SCHEMA ADMINISTRACION;
CREATE SCHEMA CONFIGURACION;
CREATE SCHEMA VENTAS;
CREATE SCHEMA CAJA;
CREATE SCHEMA INVENTARIO;
CREATE SCHEMA REPORTES;
CREATE SCHEMA CONTABILIDAD;	
CREATE SCHEMA COMPRAS;